[versions]
project-version = "0.0.1"
jdk-version = "25"

kotlin-version = "2.3.0"
ktor-version = "3.3.3"
koin-version = "4.2.0-beta3"
koin-annotations-version = "2.3.2-Beta1"
exposed-version = "1.0.0-rc-4"
postgresql = "42.7.9"
hikaricp = "7.0.2"
kotlin-logging-jvm = "7.0.14"
ktor-openapi-tools = "5.4.0"
ksp = "2.3.4"
cohort = "2.8.2"
cohort-http = "2.4.1"
ktfmt = "0.25.0"
kafka = "4.1.1"
reactor-kafka = "1.3.25"
testcontainers = "1.21.4"
retrofit = "3.0.0"
okio = "3.16.4"
retrofit-kotlinx-serialization = "1.0.0"


[libraries]
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor-version" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations-version" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations-version" }
cohort-ktor = { module = "com.sksamuel.cohort:cohort-ktor", version.ref = "cohort" }
cohort-logback = { module = "com.sksamuel.cohort:cohort-logback", version.ref = "cohort" }
cohort-hikari = { module = "com.sksamuel.cohort:cohort-hikari", version.ref = "cohort" }
cohort-http = { module = "com.sksamuel.cohort:cohort-http", version.ref = "cohort-http" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-okhttp-jvm = { module = "io.ktor:ktor-client-okhttp-jvm", version.ref = "ktor-version" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
reactor-kafka = { module = "io.projectreactor.kafka:reactor-kafka", version.ref = "reactor-kafka" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
retrofit-kotlinx-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlinx-serialization" }
ktor-openapi = { module = "io.github.smiley4:ktor-openapi", version.ref = "ktor-openapi-tools" }
ktor-swagger-ui = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "ktor-openapi-tools" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }

